{{- if and (.Values.c21srv.enabled) (eq .Values.CHAT21_ENGINE "mqtt") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiledesk.fullname" . }}-c21srv
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: c21srv
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels: {{ include "tiledesk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: c21srv
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels: {{ include "tiledesk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: c21srv
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiledesk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.c21srv.image.repository }}:{{ .Values.c21srv.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.c21srv.image.pullPolicy }}
          env:                                             
            - name: APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_APPID 
            - name: WEBHOOK_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WEBHOOK_ENDPOINTS
            - name: WEBHOOK_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WEBHOOK_ENABLED 
            - name: WEBHOOK_EVENTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WEBHOOK_EVENTS
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_MONGODB_URI
            - name: RABBITMQ_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_SRV_RABBITMQ_URI
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
