apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tiledesk.fullname" . }}-config
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
data:
  CHAT21_ENABLED: {{ .Values.CHAT21_ENABLED | quote }}

  CHAT21_ENGINE: {{ .Values.CHAT21_ENGINE | quote }}
  CHAT21_APPID: {{ .Values.CHAT21_APPID | quote }}

  RESTHOOK_ENABLED: {{ .Values.RESTHOOK_ENABLED | quote }}

  CHAT21_URL: {{ .Values.CHAT21_URL | quote }}
  CHAT21_URL_INTERNAL: {{if eq .Values.CHAT21_ENGINE "mqtt" }}http://{{ include "tiledesk.fullname" . }}-c21httpsrv{{ else }}{{ .Values.CHAT21_URL | quote }}{{ end }}

  CHAT21_ADMIN_TOKEN: {{ .Values.CHAT21_ADMIN_TOKEN | quote }}
  CHAT21_JWT_SECRET: {{ .Values.CHAT21_JWT_SECRET | quote }}


  FIREBASE_CLIENT_EMAIL: {{ .Values.FIREBASE_CLIENT_EMAIL | quote }}
  FIREBASE_PROJECT_ID: {{ .Values.FIREBASE_PROJECT_ID | quote }}
  FIREBASE_APIKEY: {{ .Values.FIREBASE_APIKEY | quote }}
  FIREBASE_AUTHDOMAIN: {{ .Values.FIREBASE_AUTHDOMAIN | quote }}
  FIREBASE_DATABASEURL: {{ .Values.FIREBASE_DATABASEURL | quote }}
  FIREBASE_STORAGEBUCKET: {{ .Values.FIREBASE_STORAGEBUCKET | quote }}
  FIREBASE_MESSAGINGSENDERID: {{ .Values.FIREBASE_MESSAGINGSENDERID | quote }}
  FIREBASE_APP_ID: {{ .Values.FIREBASE_APP_ID | quote }}
  FIREBASE_VAPID: {{ .Values.FIREBASE_VAPID | quote }}

  API_URL: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.API_URL)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.API_URL }}"{{ else }}{{ .Values.API_URL | quote }}{{ end }}
  UPLOAD_ENGINE: {{ .Values.UPLOAD_ENGINE | quote }}
  API_BASEIMAGE_URL: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.API_BASEIMAGE_URL)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.API_BASEIMAGE_URL }}"{{ else }}{{ .Values.API_BASEIMAGE_URL | quote }}{{ end }}

  MQTT_APPID: {{ .Values.MQTT_APPID | quote }}
  
  MQTT_ENDPOINT: {{if and .Values.EXTERNAL_MQTT_BASE_URL (hasPrefix "/" .Values.MQTT_ENDPOINT)}}"{{ .Values.EXTERNAL_MQTT_BASE_URL  }}{{ .Values.MQTT_ENDPOINT }}"{{ else }}{{ .Values.MQTT_ENDPOINT | quote }}{{ end }}
  MQTT_APIENDPOINT: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.MQTT_APIENDPOINT)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.MQTT_APIENDPOINT }}"{{ else }}{{ .Values.MQTT_APIENDPOINT | quote }}{{ end }}

  FEATURES_TOKEN: {{ .Values.FEATURES_TOKEN | quote }}
  SERVER_BASE_URL: {{ .Values.SERVER_BASE_URL | quote }}
  CHAT_BASE_URL: {{ .Values.CHAT_BASE_URL | quote }}
  WS_SERVER_PATH: {{ .Values.WS_SERVER_PATH | quote }}
  WS_URL_RELATIVE: {{ .Values.WS_URL_RELATIVE | quote }}
  WIDGET_LOCATION: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.WIDGET_LOCATION)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.WIDGET_LOCATION }}"{{ else }}{{ .Values.WIDGET_LOCATION | quote }}{{ end }}

  WIDGET_TEST_LOCATION: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.WIDGET_TEST_LOCATION)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.WIDGET_TEST_LOCATION }}"{{ else }}{{ .Values.WIDGET_TEST_LOCATION | quote }}{{ end }}

  PUSH_ENGINE: {{ .Values.PUSH_ENGINE | quote }}
  FIREBASE_TENANT: {{ .Values.FIREBASE_TENANT | quote }}
  
  FILE_UPLOAD_ACCEPT: {{ .Values.FILE_UPLOAD_ACCEPT | quote }}

  TRANSLATIONS_URL: {{if and .Values.EXTERNAL_BASE_URL (hasPrefix "/" .Values.TRANSLATIONS_URL)}}"{{ .Values.EXTERNAL_BASE_URL  }}{{ .Values.TRANSLATIONS_URL }}"{{ else }}{{ .Values.TRANSLATIONS_URL | quote }}{{ end }}

  DASHBOARD_URL: {{ .Values.DASHBOARD_URL | quote }}

  AUTH_PERSISTENCE: {{ .Values.AUTH_PERSISTENCE | quote }}
  
  EMAIL_ENABLED: {{ .Values.EMAIL_ENABLED | quote }}
  EMAIL_HOST: {{ .Values.EMAIL_HOST | quote }}
  EMAIL_USERNAME: {{ .Values.EMAIL_USERNAME | quote }}
  EMAIL_SECURE: {{ .Values.EMAIL_SECURE | quote }}
  EMAIL_PORT: {{ .Values.EMAIL_PORT | quote }}
  EMAIL_PASSWORD: {{ .Values.EMAIL_PASSWORD | quote }}
  EMAIL_BASEURL: {{ .Values.EMAIL_BASEURL | quote }}

  EMAIL_FROM_ADDRESS: {{ .Values.EMAIL_FROM_ADDRESS | quote }}
  {{if .Values.EMAIL_BCC}}EMAIL_BCC: {{ .Values.EMAIL_BCC | quote }}{{ end }}
  {{if .Values.EMAIL_ASSIGN_REQUEST_HTML_TEMPLATE}}EMAIL_ASSIGN_REQUEST_HTML_TEMPLATE: {{ .Values.EMAIL_ASSIGN_REQUEST_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_ASSIGN_MESSAGE_EMAIL_HTML_TEMPLATE}}EMAIL_ASSIGN_MESSAGE_EMAIL_HTML_TEMPLATE: {{ .Values.EMAIL_ASSIGN_MESSAGE_EMAIL_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_POOLED_REQUEST_HTML_TEMPLATE}}EMAIL_POOLED_REQUEST_HTML_TEMPLATE: {{ .Values.EMAIL_POOLED_REQUEST_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_POOLED_MESSAGE_EMAIL_HTML_TEMPLATE}}EMAIL_POOLED_MESSAGE_EMAIL_HTML_TEMPLATE: {{ .Values.EMAIL_POOLED_MESSAGE_EMAIL_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_NEW_MESSAGE_HTML_TEMPLATE}}EMAIL_NEW_MESSAGE_HTML_TEMPLATE: {{ .Values.EMAIL_NEW_MESSAGE_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_TICKET_HTML_TEMPLATE}}EMAIL_TICKET_HTML_TEMPLATE: {{ .Values.EMAIL_TICKET_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_RESET_PASSWORD_HTML_TEMPLATE}}EMAIL_RESET_PASSWORD_HTML_TEMPLATE: {{ .Values.EMAIL_RESET_PASSWORD_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_PASSWORD_CHANGED_HTML_TEMPLATE}}EMAIL_PASSWORD_CHANGED_HTML_TEMPLATE: {{ .Values.EMAIL_PASSWORD_CHANGED_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_NEWUSER_INVITED_HTML_TEMPLATE}}EMAIL_NEWUSER_INVITED_HTML_TEMPLATE: {{ .Values.EMAIL_NEWUSER_INVITED_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_VERIFY_HTML_TEMPLATE}}EMAIL_VERIFY_HTML_TEMPLATE: {{ .Values.EMAIL_VERIFY_HTML_TEMPLATE | quote }}{{ end }}
  {{if .Values.EMAIL_SEND_TRANSCRIPT_HTML_TEMPLATE}}EMAIL_SEND_TRANSCRIPT_HTML_TEMPLATE: {{ .Values.EMAIL_SEND_TRANSCRIPT_HTML_TEMPLATE | quote }}{{ end }}
  
  LOG_LEVEL: {{ .Values.LOG_LEVEL | quote }}
  MONGODB_LOGS_URI: {{ .Values.MONGODB_LOGS_URI | quote }}

  MONGODB_URI: {{if .Values.MONGODB_URI}}{{ .Values.MONGODB_URI | quote }}{{ else }}mongodb://{{ include "tiledesk.fullname" . }}-mongodb/tiledesk{{ end }}

  CHAT21_MONGODB_URI: {{if .Values.CHAT21_MONGODB_URI}}{{ .Values.CHAT21_MONGODB_URI | quote }}{{ else }}mongodb://{{ include "tiledesk.fullname" . }}-mongodb/chat21{{ end }}
  

  SUPER_PASSWORD: {{ .Values.SUPER_PASSWORD | quote }}

  RESTHOOK_ENABLED: {{ .Values.RESTHOOK_ENABLED | quote }}

  
  CHAT21_SRV_RABBITMQ_URI: {{if .Values.CHAT21_SRV_RABBITMQ_URI}}{{ .Values.CHAT21_SRV_RABBITMQ_URI | quote }}{{ else }}amqp://{{ .Values.CHAT21_SRV_RABBITMQ_CREDENTIAL }}@{{ include "tiledesk.fullname" . }}-rabbitmq:5672?heartbeat=60{{ end }}
  CHAT21_HTTPSRV_RABBITMQ_URI: {{if .Values.CHAT21_HTTPSRV_RABBITMQ_URI}}{{ .Values.CHAT21_HTTPSRV_RABBITMQ_URI | quote }}{{ else }}amqp://{{ .Values.CHAT21_HTTPSRV_RABBITMQ_CREDENTIAL }}@{{ include "tiledesk.fullname" . }}-rabbitmq:5672?heartbeat=60{{ end }}
    
  
  JWT_KEY: {{ .Values.JWT_KEY | quote }}

  APP_ID: {{ .Values.APP_ID | quote }}

  WEBHOOK_ENABLED: {{ .Values.WEBHOOK_ENABLED | quote }}
  WEBHOOK_ORIGIN: {{ .Values.WEBHOOK_ORIGIN | quote }}
  WEBHOOK_EVENTS: {{ .Values.WEBHOOK_EVENTS | quote }}
  WEBHOOK_ENDPOINTS: http://{{ include "tiledesk.fullname" . }}-server/chat21/requests,http://{{ include "tiledesk.fullname" . }}-c21httpsrv/api/tilechat/push/webhook/endpoint/WHFyAhecCMkYsvldLFWbSrJt7lAZFAmrp7O5QVMvGQsLVn9SkfT
  
  
  
  SUPPORT_MODE: {{ .Values.SUPPORT_MODE | quote }}
  WRITE_TO_BUTTON: {{ .Values.WRITE_TO_BUTTON | quote }}
  ARCHIVED_BUTTON: {{ .Values.ARCHIVED_BUTTON | quote }}
  AUTH_PERSISTENCE: {{ .Values.AUTH_PERSISTENCE | quote }}

  PUSH_ENABLED: {{ .Values.PUSH_ENABLED | quote }}
  PUSH_WH_WEBHOOK_TOKEN: {{ .Values.PUSH_WH_WEBHOOK_TOKEN | quote }}
  PUSH_WH_NOTIFY_URL: {{ .Values.PUSH_WH_NOTIFY_URL | quote }}
  PUSH_WH_CHAT21_API_ADMIN_TOKEN: {{ .Values.PUSH_WH_CHAT21_API_ADMIN_TOKEN | quote }}
  WEB_CLICK_ACTION: {{ .Values.WEB_CLICK_ACTION | quote }}
  
  SYNC_CHAT21_GROUPS: {{ .Values.SYNC_CHAT21_GROUPS | quote }}