{{- if .Values.ionic.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiledesk.fullname" . }}-ionic
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: ionic
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels: {{ include "tiledesk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ionic
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels: {{ include "tiledesk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ionic
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiledesk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ionic.image.repository }}:{{ .Values.ionic.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ionic.image.pullPolicy }}
          env:                                 
            - name: API_URL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: API_URL
            - name: CHAT21_ENGINE
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: CHAT21_ENGINE    
            - name: MQTT_APPID
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: MQTT_APPID
            - name: MQTT_ENDPOINT
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: MQTT_ENDPOINT  
            - name: MQTT_APIENDPOINT
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: MQTT_APIENDPOINT  
            - name: UPLOAD_ENGINE
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: UPLOAD_ENGINE
            - name: PUSH_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: PUSH_ENGINE
            - name: FIREBASE_TENANT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_TENANT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: LOG_LEVEL
            - name: FILE_UPLOAD_ACCEPT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FILE_UPLOAD_ACCEPT
            - name: CHAT21_URL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: CHAT21_URL
            - name: DASHBOARD_URL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: DASHBOARD_URL
            - name: API_BASEIMAGE_URL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: API_BASEIMAGE_URL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_PROJECT_ID
            - name: FIREBASE_APIKEY
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_APIKEY
            - name: FIREBASE_AUTHDOMAIN
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_AUTHDOMAIN
            - name: FIREBASE_DATABASEURL
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_DATABASEURL
            - name: FIREBASE_STORAGEBUCKET
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_STORAGEBUCKET
            - name: FIREBASE_MESSAGINGSENDERID
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_MESSAGINGSENDERID
            - name: FIREBASE_APP_ID
              valueFrom:
                  configMapKeyRef:
                    name: {{ include "tiledesk.fullname" . }}-config
                    key: FIREBASE_APP_ID
          ports:
            - name: ionic-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ionic-http
          readinessProbe:
            httpGet:
              path: /
              port: ionic-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
