apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiledesk.fullname" . }}
  labels: {{ include "tiledesk.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.server.superPassword }}
  super-password: {{ .Values.server.superPassword | b64enc | quote }}
  {{ else }}
  super-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  firebase-privatekey: {{ .Values.FIREBASE_PRIVATE_KEY | b64enc | quote }}
  global-public-key: {{ .Values.GLOBAL_SECRET_OR_PUB_KEY | b64enc | quote }}
  global-private-key: {{ .Values.GLOBAL_SECRET_OR_PRIVATE_KEY | b64enc | quote }}