{{- if .Values.server.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tiledesk.fullname" . }}-server
  labels:
    {{- include "tiledesk.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "tiledesk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "tiledesk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tiledesk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:   
            - name: WS_SERVER_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WS_SERVER_PATH
            - name: CHAT21_JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_JWT_SECRET 
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tiledesk.fullname" . }}
                  key: firebase-privatekey
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: FIREBASE_PROJECT_ID
            - name: CHAT21_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_ENABLED
            - name: CHAT21_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_ENGINE                  
            - name: CHAT21_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_URL_INTERNAL
            - name: CHAT21_APPID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_APPID
            - name: CHAT21_ADMIN_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: CHAT21_ADMIN_TOKEN          
            - name: EMAIL_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_BASEURL
            - name: EMAIL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_ENABLED
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_HOST
            - name: EMAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_USERNAME
            - name: EMAIL_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_SECURE
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_PORT             
            - name: EMAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: EMAIL_PASSWORD    
            - name: SUPER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: SUPER_PASSWORD
            - name: WIDGET_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WIDGET_LOCATION
            - name: WIDGET_TEST_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WIDGET_TEST_LOCATION                  
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: MONGODB_URI
            - name: MONGODB_LOGS_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: MONGODB_LOGS_URI
            - name: RESTHOOK_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: RESTHOOK_ENABLED
            - name: WEBHOOK_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tiledesk.fullname" . }}-config
                  key: WEBHOOK_ORIGIN
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: tiledesk-license
                  key: licensekey
                  optional: true
          ports:
            - name: server-http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: server-http
          readinessProbe:
            httpGet:
              path: /
              port: server-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
