# Default values for tiledesk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Tiledesk Server
## ref: https://developer.tiledesk.com/
##
 
CHAT21_ENABLED: true

#choose one of the following:
CHAT21_ENGINE: mqtt
#CHAT21_ENGINE: firebase

CHAT21_APPID: tilechat

## Native Chat21 Engine start
CHAT21_URL: /chatapi/

CHAT21_ADMIN_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzNDU2MTBkNy03MmYxLTQ5OWUtODQzMS0xMTNhZWJkOWVmOTgiLCJzdWIiOiIxMDAtQVBJQURNSU4iLCJzY29wZSI6WyJyYWJiaXRtcS5yZWFkOiovKi8qIiwicmFiYml0bXEud3JpdGU6Ki8qLyoiLCJyYWJiaXRtcS5jb25maWd1cmU6Ki8qLyoiXSwiY2xpZW50X2lkIjoiMTAwLUFQSUFETUlOIiwiY2lkIjoiMTAwLUFQSUFETUlOIiwiYXpwIjoiMTAwLUFQSUFETUlOIiwidXNlcl9pZCI6IjEwMC1BUElBRE1JTiIsImFwcF9pZCI6InRpbGVjaGF0IiwiaWF0IjoxNjE0OTQzNDkyLCJleHAiOjE5MjU5ODM0OTIsImF1ZCI6WyJyYWJiaXRtcSIsIjEwMC1BUElBRE1JTiJdLCJraWQiOiJ0aWxlZGVzay1rZXkiLCJ0aWxlZGVza19hcGlfcm9sZXMiOiJhZG1pbiJ9.KptGMsTKjd3wUiiP1GGSTYqW1XXK1vjSRJnetC3wjxU
CHAT21_JWT_SECRET: tokenKey
## Native Chat21 Engine end

## Firebase Chat21 Engine - Start

#CHAT21_URL: https://CHANGEIT.cloudfunctions.net
#CHAT21_ADMIN_TOKEN: chat21-secret-orgAa,
# optional properties for tiledesk-server docker installation but required for docker-compose used by clients (dashboard, ionic, widget)
PUSH_ENABLED: false
PUSH_WH_WEBHOOK_TOKEN: WHFyAhecCMkYsvldLFWbSrJt7lAZFAmrp7O5QVMvGQsLVn9SkfT
PUSH_WH_NOTIFY_URL: http://localhost:8004/api/tilechat/notify
PUSH_WH_CHAT21_API_ADMIN_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5NGFjNjNmNy1hOGM3LTRkZGMtYjJkNS01MWE2MjBmNTdhNmIiLCJzdWIiOiIxMDAtQVBJQURNSU4iLCJzY29wZSI6WyJyYWJiaXRtcS5yZWFkOiovKi8qIiwicmFiYml0bXEud3JpdGU6Ki8qLyoiLCJyYWJiaXRtcS5jb25maWd1cmU6Ki8qLyoiXSwiY2xpZW50X2lkIjoiMTAwLUFQSUFETUlOIiwiY2lkIjoiMTAwLUFQSUFETUlOIiwiYXpwIjoiMTAwLUFQSUFETUlOIiwidXNlcl9pZCI6IjEwMC1BUElBRE1JTiIsImFwcF9pZCI6InRpbGVjaGF0IiwiaWF0IjoxNjM3NzYxNDM0LCJleHAiOjE5NDg4MDE0MzQsImF1ZCI6WyJyYWJiaXRtcSIsIjEwMC1BUElBRE1JTiJdLCJraWQiOiJ0aWxlZGVzay1rZXkiLCJ0aWxlZGVza19hcGlfcm9sZXMiOiJhZG1pbiJ9.fLPrGArRlnyC04552oBsUjohf6l_BIpxwB847xWvugo

FIREBASE_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----\nCHANGEIT\n-----END PRIVATE KEY-----\n
FIREBASE_CLIENT_EMAIL: CHANGEIT@CHANGEIT.com
FIREBASE_PROJECT_ID: CHANGEIT
FIREBASE_APIKEY: CHANGEIT
FIREBASE_AUTHDOMAIN: CHANGEIT.firebaseapp.com
FIREBASE_DATABASEURL: https://CHANGEIT.firebaseio.com
FIREBASE_STORAGEBUCKET: CHANGEIT.appspot.com
FIREBASE_MESSAGINGSENDERID: CHANGEIT
FIREBASE_APP_ID: CHANGEIT
FIREBASE_VAPID: CHANGEIT

## Firebase Chat21 Engine - End


#Optional properties
#MONGODB_URI: mongodb://tiledesk-mongo/tiledesk

#EXTERNAL_BASE_URL: http://console.tiledesk.local
#EXTERNAL_MQTT_BASE_URL: ws://console.tiledesk.local

# Shared Config

API_URL: /api/
UPLOAD_ENGINE: native
API_BASEIMAGE_URL: /api/
MQTT_APPID: tilechat
MQTT_ENDPOINT: /mqws/ws
MQTT_APIENDPOINT: /chatapi/api
PUSH_ENGINE: none
FIREBASE_TENANT: tilechat
FILE_UPLOAD_ACCEPT: "*/*"


# Dashboard Config
FEATURES_TOKEN: "NAT:T-DEV:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-LBS:T-NOT:T-MTT:T-RAS:T"
SERVER_BASE_URL: /api/
CHAT_BASE_URL: /chat/
WS_SERVER_PATH: /
WS_URL_RELATIVE: /ws/
WIDGET_LOCATION: /widget/launch.js
WIDGET_TEST_LOCATION: /widget/assets/twp/index.html

# Widget Config
TRANSLATIONS_URL: /api/
AUTH_PERSISTENCE: LOCAL

# Ionic Config
DASHBOARD_URL: /dashboard/
SUPPORT_MODE: true
WRITE_TO_BUTTON: true
ARCHIVED_BUTTON: true
WEB_CLICK_ACTION: CHANGEIT #move to another section

# Email Config
EMAIL_ENABLED: false
EMAIL_HOST: YOUR_EMAIL_HOST
EMAIL_USERNAME: YOUR_EMAIL_USERNAME
EMAIL_SECURE: false #defaults to 587 if is secure is false or 465 if true
EMAIL_PORT: 587
EMAIL_PASSWORD: CHANGEIT
EMAIL_BASEURL: http://console.tiledesk.local/dashboard

EMAIL_FROM_ADDRESS: CHANGEIT
#EMAIL_BCC:
#EMAIL_ASSIGN_REQUEST_HTML_TEMPLATE: 
#EMAIL_ASSIGN_MESSAGE_EMAIL_HTML_TEMPLATE:
#EMAIL_POOLED_REQUEST_HTML_TEMPLATE:
#EMAIL_POOLED_MESSAGE_EMAIL_HTML_TEMPLATE:
#EMAIL_NEW_MESSAGE_HTML_TEMPLATE:
#EMAIL_TICKET_HTML_TEMPLATE:
#EMAIL_RESET_PASSWORD_HTML_TEMPLATE:
#EMAIL_PASSWORD_CHANGED_HTML_TEMPLATE:
#EMAIL_NEWUSER_INVITED_HTML_TEMPLATE:
#EMAIL_VERIFY_HTML_TEMPLATE:
#EMAIL_SEND_TRANSCRIPT_HTML_TEMPLATE:

# Log Config
LOG_LEVEL: info
MONGODB_LOGS_URI: CHANGEIT

# Server Config
SUPER_PASSWORD: superadmin

# Modules Config
RESTHOOK_ENABLED: true


# Shared Chat21 Server Config
#LOG_LEVEL: info
#CHAT21_MONGODB_URI: mongodb://mongo/chat21

# Chat21 Http Server Config
JWT_KEY: tokenKey
#CHAT21_SRV_RABBITMQ_URI: amqp://ignored:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2YWI3MzY1Yi1hYWRhLTRlNTktOWZjZS0yMDQwZDgyOTA4MTgiLCJzdWIiOiIxMDAtQVBJQURNSU4iLCJzY29wZSI6WyJyYWJiaXRtcS5yZWFkOiovKi8qIiwicmFiYml0bXEud3JpdGU6Ki8qLyoiLCJyYWJiaXRtcS5jb25maWd1cmU6Ki8qLyoiXSwiY2xpZW50X2lkIjoiMTAwLUFQSUFETUlOIiwiY2lkIjoiMTAwLUFQSUFETUlOIiwiYXpwIjoiMTAwLUFQSUFETUlOIiwidXNlcl9pZCI6IjEwMC1BUElBRE1JTiIsImFwcF9pZCI6InRpbGVjaGF0IiwiaWF0IjoxNTk0Mzc3OTc4LCJleHAiOjE2OTY5Njk5NzgsImF1ZCI6WyJyYWJiaXRtcSIsIjEwMC1BUElBRE1JTiJdLCJraWQiOiJ0aWxlZGVzay1rZXkiLCJ0aWxlZGVza19hcGlfcm9sZXMiOiJhZG1pbiJ9.g2YL6RZp5SuLcQyBTYf4cn9SnRIyifNb1f1-Si1inbs@rabbitmq:5672?heartbeat=60

CHAT21_SRV_RABBITMQ_CREDENTIAL: ignored:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyMDI2NjU0Ni05ZGMxLTQ3MzgtOWE5OC01OTQwYWFmZWJkMjgiLCJzdWIiOiIwMS1PQlNFUlZFUiIsInNjb3BlIjpbInJhYmJpdG1xLnJlYWQ6Ki8qLyoiLCJyYWJiaXRtcS53cml0ZToqLyovKiIsInJhYmJpdG1xLmNvbmZpZ3VyZToqLyovKiJdLCJjbGllbnRfaWQiOiIwMS1PQlNFUlZFUiIsImNpZCI6IjAxLU9CU0VSVkVSIiwiYXpwIjoiMDEtT0JTRVJWRVIiLCJ1c2VyX2lkIjoiMDEtT0JTRVJWRVIiLCJhcHBfaWQiOiJ0aWxlY2hhdCIsImlhdCI6MTU5Mzg1OTgzNiwiZXhwIjoxNjk2NDUxODM2LCJhdWQiOlsicmFiYml0bXEiLCIwMS1PQlNFUlZFUiJdLCJraWQiOiJ0aWxlZGVzay1rZXkiLCJ0aWxlZGVza19hcGlfcm9sZXMiOiJ1c2VyIn0.N6bs-WXVZJTNW2jztzph4SYc9_Szs0cb0kBM9n0k8hY

# Chat21 Server Config
APP_ID: tilechat
WEBHOOK_ENABLED: true
WEBHOOK_ORIGIN: http://api.tiledesk.local
WEBHOOK_EVENTS: message-sent,message-delivered
SYNC_CHAT21_GROUPS: false

CHAT21_HTTPSRV_RABBITMQ_CREDENTIAL: ignored:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2YWI3MzY1Yi1hYWRhLTRlNTktOWZjZS0yMDQwZDgyOTA4MTgiLCJzdWIiOiIxMDAtQVBJQURNSU4iLCJzY29wZSI6WyJyYWJiaXRtcS5yZWFkOiovKi8qIiwicmFiYml0bXEud3JpdGU6Ki8qLyoiLCJyYWJiaXRtcS5jb25maWd1cmU6Ki8qLyoiXSwiY2xpZW50X2lkIjoiMTAwLUFQSUFETUlOIiwiY2lkIjoiMTAwLUFQSUFETUlOIiwiYXpwIjoiMTAwLUFQSUFETUlOIiwidXNlcl9pZCI6IjEwMC1BUElBRE1JTiIsImFwcF9pZCI6InRpbGVjaGF0IiwiaWF0IjoxNTk0Mzc3OTc4LCJleHAiOjE2OTY5Njk5NzgsImF1ZCI6WyJyYWJiaXRtcSIsIjEwMC1BUElBRE1JTiJdLCJraWQiOiJ0aWxlZGVzay1rZXkiLCJ0aWxlZGVza19hcGlfcm9sZXMiOiJhZG1pbiJ9.g2YL6RZp5SuLcQyBTYf4cn9SnRIyifNb1f1-Si1inbs

server:
  ## Enable deployment of Tiledesk Server
  ##
  enabled: true

  image:  
    repository: tiledesk/tiledesk-server
    tag: 2.2.39

  service:
    type: ClusterIP
    port: 80

dashboard:
  ## Enable deployment of Tiledesk Server
  ##
  enabled: true

  image:
    repository: tiledesk/tiledesk-dashboard
    tag: 2.2.43.2

  service:
    type: ClusterIP
    port: 80

ionic:
  ## Enable deployment of Tiledesk Server
  ##
  enabled: true

  image:
    repository: chat21/chat21-ionic
    tag: 3.0.69

  service:
      type: ClusterIP
      port: 80
    # pullPolicy: IfNotPresent
 
webwidget:
  ## Enable deployment of Tiledesk Server
  ##
  enabled: true

  image:
    repository: chat21/chat21-web-widget
    tag: 5.0.27

  service:
      type: ClusterIP
      port: 80
    # pullPolicy: IfNotPresent

c21httpsrv:
  ## Enable deployment of Chat21 http Server
  ##
  enabled: true

  image:  
    repository: chat21/chat21-http-server
    tag: 0.2.9
    # pullPolicy: IfNotPresent  

  service:    
    type: ClusterIP
    port: 80
    
c21srv:
  ## Enable deployment of Chat21 Server
  ##
  enabled: true

  image:  
    repository: chat21/chat21-server
    tag: 0.2.11
    # pullPolicy: IfNotPresent  

imagePullSecrets: #[]
  - name: tiledesk-enterprise-image-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


service: #do not remove used by ingress-proxy-nginx
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx #deprecated
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/firebase-messaging-sw.js /chat/firebase-messaging-sw.js last;
  hosts:
    - host:
      enabled: true
      paths: 
        - path: /api/(.*)
          service: server
        - path: /ws/(.*)
          service: server
        - path: /dashboard/(.*)
          service: dashboard
        - path: /chat/(.*)
          service: ionic
        - path: /widget/(.*)
          service: webwidget
        - path: /widget-config.json
          service: webwidget
        - path: /mqws/(.*)
          service: rabbitmq
          servicePort: 15675
        # - path: /mq
        #   service: rabbitmq
        - path: /chatapi/(.*)
          service: c21httpsrv
    - host: console.tiledesk.local
      enabled: false
      paths: 
        - path: /api/(.*)
          service: server
        - path: /ws/(.*)
          service: server
        - path: /dashboard/(.*)
          service: dashboard
        - path: /chat/(.*)
          service: ionic
        - path: /widget/(.*)
          service: webwidget
        - path: /widget-config.json
          service: webwidget
        - path: /mqws/(.*)
          service: rabbitmq
          servicePort: 15675
        # - path: /mq/(.*)
        #   service: rabbitmq
        - path: /chatapi/(.*)
          service: c21httpsrv
    - host: api.tiledesk.local
      enabled: false
      paths: 
        - path: /(.*)
          service: server
    - host: rtm.tiledesk.local
      enabled: false
      paths: 
        - path: /(.*)
          service: server
    - host: widget.tiledesk.local 
      enabled: false
      paths: 
        - path: /(.*)
          service: webwidget

  tls: []
    #  - secretName: tiledesk-tls-secret
    #    hosts:
    #      - console.tiledesk.local
    #      - api.tiledesk.local


# ## Enable persistence using Persistent Volume Claims
# ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
# ##
# persistence:
#   enabled: false
#   ## parse data Persistent Volume Storage Class
#   ## If defined, storageClassName: <storageClass>
#   ## If set to "-", storageClassName: "", which disables dynamic provisioning
#   ## If undefined (the default) or set to null, no storageClassName spec is
#   ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
#   ##   GKE, AWS & OpenStack)
#   ##
#   # storageClass: "-"
#   accessMode: ReadWriteOnce
#   size: 8Gi

##
## MongoDB chart configuration
##
## https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
##
mongodb:
  enabled: true
  nameOverride: mongodb

  # replicaSet: 
  #   enabled: false
  auth:
    enabled: false
  ## If the password is not specified, MongoDB will generate a random password
  ##
  # mongodbRootPassword:
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: true
    resourcePolicy: "keep"
    size: 3Gi

rabbitmq: #consumer_timeout = 31622400000
  #fullnameOverride: rabbitmq
  enabled: true
  auth:
    username: rabbitmq
    password: rabbitmq-password-changeit
    erlangCookie: erlangCookie
  service:
     type: ClusterIP
     extraPorts: 
      - name: mqtt-tcp
        port: 1883
        targetPort: 1883
      - name: mqtt-web
        port: 15675
        targetPort: 15675     
  extraPlugins: "rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_auth_backend_oauth2 rabbitmq_federation_management rabbitmq_stomp"
  extraConfiguration: |-
    mqtt.listeners.tcp.default = 1883
    ## Default MQTT with TLS port is 8883
    # mqtt.listeners.ssl.default = 8883

    # anonymous connections, if allowed, will use the default
    # credentials specified here
    mqtt.allow_anonymous  = true
    mqtt.default_user     = guest
    mqtt.default_pass     = guest

    mqtt.vhost            = /
    mqtt.exchange         = amq.topic
    # 24 hours by default
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch         = 10
  advancedConfiguration: |-
    [
        % Enable auth backend
        {rabbit, [
            {auth_backends, [rabbit_auth_backend_oauth2]}
        ]},

        % Set a resource server ID. Will require all scopes to be prefixed with rabbitmq.
        {rabbitmq_auth_backend_oauth2, [
            {resource_server_id, <<"rabbitmq">>},
            % Set up a legacy signing key
            {key_config, [
                {default_key, <<"legacy-token-key">>},
                {signing_keys, #{
                    <<"legacy-token-key">> =>
                        {map, #{
                            <<"alg">> => <<"HS256">>,
                            <<"value">> => <<"tokenKey">>,
                            <<"kty">> => <<"MAC">>}
                        } % end map
                    } % end signing_keys map
                } % end signing_keys
            ]} % end key_config
        ]} % end rabbitmq_auth_backend_oauth2
    ].

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
